### **Nombre:** Elda Magally Calderón Motta
### **Carné:** 16003182
### **Sección:** U

# **TAREA 4**

# XOR con Composicion y Perceptrones

## Parte 1

In [1]:
import numpy as np

In [398]:
def fun_not(X1):
    x = np.array([X1,1])
    parametros = np.array([-1,1])
    res = int(np.sum(x * parametros) > 0)
    return(res)

In [40]:
fun_not(1)

0

In [399]:
def fun_or(X1,X2):
    x = np.array([X1,X2,1])
    parametros = np.array([1,1,0])
    res = int(np.sum(x * parametros) > 0)
    return(res)

In [400]:
fun_or(0,0)

0

In [32]:
def fun_and(X1,X2):
    x = np.array([X1,X2,1])
    parametros = np.array([1,1,-1])
    res = int(np.sum(x * parametros) > 0)
    return(res)

In [37]:
fun_and(0,0)

0

In [41]:
def fun_xor(X1,X2):
    temp1 = fun_and(X1,X2)
    temp2 = fun_or(X1,X2)
    temp3 = fun_not(temp1)
    temp4 = fun_and(temp2, temp3)
    return(temp4)

In [45]:
fun_xor(1,1)

0

## Parte 2

### Entrenamiento Perceptron OR

In [457]:
datos = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
real = np.array([[0],[1],[1],[1]])

In [431]:
inicio = np.array([[10,10,1]])
lr = 0.1
parametros = inicio

In [432]:
for j in range(15):
    for i in range(datos.shape[0]):
        it = int(np.sum(datos[i] * parametros) > 0)
        if (it > 0 and real[i] == 0):
            parametros = np.sum(parametros - lr * datos[i], axis = 0).reshape(1,3)
        elif (it < 0 and real[i] == 1):
            parametros = np.sum(parametros + lr * datos[i], axis = 0).reshape(1,3)
    print(parametros)

[[10.  10.   0.9]]
[[10.  10.   0.8]]
[[10.  10.   0.7]]
[[10.  10.   0.6]]
[[10.  10.   0.5]]
[[10.  10.   0.4]]
[[10.  10.   0.3]]
[[10.  10.   0.2]]
[[10.  10.   0.1]]
[[1.00000000e+01 1.00000000e+01 1.38777878e-16]]
[[10.  10.  -0.1]]
[[10.  10.  -0.1]]
[[10.  10.  -0.1]]
[[10.  10.  -0.1]]
[[10.  10.  -0.1]]


In [459]:
def fun_or2(X1,X2):
    x = np.array([X1,X2,1])
    w = np.array([parametros[0,0],parametros[0,1],parametros[0,2]])
    res = int(np.sum(x * w) > 0)
    return(res)

In [460]:
fun_or2(0,0)

0

### Entrenamiento Perceptron AND

In [458]:
datos2 = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
real2 = np.array([[0],[0],[0],[1]])

In [450]:
inicio2 = np.array([[8,8,1]])
lr2 = 0.1
parametros2 = inicio2

In [451]:
for j in range(40):
    for i in range(datos2.shape[0]):
        it2 = int(np.sum(datos2[i] * parametros2) > 0)
        if (it2 > 0 and real2[i] == 0):
            parametros2 = np.sum(parametros2 - lr2 * datos2[i], axis = 0).reshape(1,3)
        elif (it2 < 0 and real2[i] == 1):
            parametros2 = np.sum(parametros2 + lr2 * datos2[i], axis = 0).reshape(1,3)
    print(parametros2)

[[7.9 7.9 0.7]]
[[7.8 7.8 0.4]]
[[7.7 7.7 0.1]]
[[ 7.6  7.6 -0.2]]
[[ 7.5  7.5 -0.4]]
[[ 7.4  7.4 -0.6]]
[[ 7.3  7.3 -0.8]]
[[ 7.2  7.2 -1. ]]
[[ 7.1  7.1 -1.2]]
[[ 7.   7.  -1.4]]
[[ 6.9  6.9 -1.6]]
[[ 6.8  6.8 -1.8]]
[[ 6.7  6.7 -2. ]]
[[ 6.6  6.6 -2.2]]
[[ 6.5  6.5 -2.4]]
[[ 6.4  6.4 -2.6]]
[[ 6.3  6.3 -2.8]]
[[ 6.2  6.2 -3. ]]
[[ 6.1  6.1 -3.2]]
[[ 6.   6.  -3.4]]
[[ 5.9  5.9 -3.6]]
[[ 5.8  5.8 -3.8]]
[[ 5.7  5.7 -4. ]]
[[ 5.6  5.6 -4.2]]
[[ 5.5  5.5 -4.4]]
[[ 5.4  5.4 -4.6]]
[[ 5.3  5.3 -4.8]]
[[ 5.2  5.2 -5. ]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]
[[ 5.1  5.1 -5.2]]


In [461]:
def fun_and2(X1,X2):
    x = np.array([X1,X2,1])
    w = np.array([parametros2[0,0],parametros2[0,1],parametros2[0,2]])
    res = int(np.sum(x * w) > 0)
    return(res)

In [464]:
fun_and2(1,1)

1

### Funcion XOR con Perceptrones Entrenados

In [465]:
def fun_xor2(X1,X2):
    temp1 = fun_and2(X1,X2)
    temp2 = fun_or2(X1,X2)
    temp3 = fun_not(temp1)
    temp4 = fun_and2(temp2, temp3)
    return(temp4)

In [470]:
fun_xor2(1,1)

0