### **Nombre:** Elda Magally Calderón Motta
### **Carné:** 16003182
### **Sección:** U

# **TAREA 6**

# Primera Parte 

## Backward Propagation Delta (Error Simplificado)

In [485]:
import numpy as np
import matplotlib.pyplot as plt

## Diagrama

<img src = 'http://imgfz.com/i/2AOBoZL.png'>

### Backward Propagation

In [486]:
# Vector error capa de salida
error_salida = np.array([[3,10]])

In [487]:
# Parametros capa 3
w_capa3 = np.array([
    [-0.23, 0.22, 0.77], 
    [0.9, 0.88, -0.4],
])

In [488]:
# Propagacion del error a la capa 3
error_capa3 = np.matmul(error_salida, w_capa3)

In [489]:
# Parametros capa 2
w_capa2 = np.array([
    [-0.3, 0.62, 0.45], 
    [0.45, 0.57, 0.48],
    [0.65, 0.58, -0.45]
])

In [490]:
# Propagacion del error a la capa 2
error_capa2 = np.matmul(error_capa3, w_capa2)

In [491]:
# Parametros capa 1
w_capa1 = np.array([
    [0.3, 0.46, 0.02], 
    [0.22, -0.7, 0.65],
    [0.65, 0.9, 0.34]
])

In [492]:
# Propagacion del error a la capa 1 (entrada)
error_capa1 = np.matmul(error_capa2, w_capa1)

In [493]:
# Errores por neurona

print('Error Neuronas Capa 1:', error_capa1)
print('Error Neuronas Capa 2:', error_capa2)
print('Error Neuronas Capa 3:', error_capa3)
print('Error Neuronas Capa Salida:', error_salida)

Error Neuronas Capa 1: [[8.180294 1.74791  9.303912]]
Error Neuronas Capa 2: [[0.6655 9.5642 9.0408]]
Error Neuronas Capa 3: [[ 8.31  9.46 -1.69]]
Error Neuronas Capa Salida: [[ 3 10]]


# Segunda Parte 

## Entrenar Aproximador para XOR

### Red Neuronal XOR

<img src = 'http://imgfz.com/i/aYX8w9y.jpeg'>

### Feedforward Propagation

In [615]:
# Vector de entrada:

vector_input = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y_real = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [616]:
# Inicilizando parametros aleatoriamente 
# Neuronas en filas

mu, sigma = 0, 0.1
w2 = np.random.normal(mu, sigma, 6).reshape(2,-1)
w3 = np.random.normal(mu, sigma, 6).reshape(3,-1)
w4 = np.random.normal(mu, sigma, 2).reshape(2,-1)

In [708]:
# Funcion Relu

def relu(x):
    a = x
    a[a < 0] = 0
    return a

In [667]:
# Representaciones Intermedias
H1 = np.matmul(vector_input, w2)
act1 = relu(H1)

In [668]:
H2 = np.matmul(act1, w3)
act2 = relu(H2)

In [669]:
H3 = np.matmul(act2, w4)
vector_output = H3

In [670]:
vector_output

array([[0.        ],
       [0.00046214],
       [0.00070501],
       [0.00116715]])

### Backward Propagation

In [621]:
# Deltas Iniciales
costo_capa4 = np.zeros(w4.shape)
costo_capa3 = np.zeros(w3.shape)
costo_capa2 = np.zeros(w2.shape)

In [501]:
# Funcion Derivada Relu

def der_relu(x):
    a = x
    a[a >= 0] = 1
    a[a < 0] = 0
    return (a)

In [671]:
# Error en Salida
error_salida = y_real - vector_output

In [681]:
delta_capa3 = np.matmul(error_salida, w4.T)*der_relu(H2)

In [673]:
delta_capa2 = np.matmul(delta_capa3, w3.T)*der_relu(H1)

In [674]:
costo_capa4 = np.matmul(error_salida.T, act2)

In [675]:
costo_capa3 = np.matmul(delta_capa3.T, act1)

In [676]:
costo_capa2 = np.matmul(delta_capa2.T, vector_input)

In [677]:
# Actualizacion de Costos
costo_capa4 += costo_capa4
costo_capa3 += costo_capa3
costo_capa2 += costo_capa2

In [678]:
# Gradiente Descent
lr = 0.1

w2 = w2 - lr*costo_capa2.T
w3 = w3 - lr*costo_capa3.T
w4 = w4 - lr*costo_capa4.T

In [679]:
print(w2)

[[ 0.02456542  0.09183525 -0.03642401]
 [ 0.06147942  0.07914314 -0.09446587]]


In [680]:
print(error_salida)

[[ 0.        ]
 [ 0.99953786]
 [ 0.99929499]
 [-0.00116715]]


# Funcion

In [709]:
# Vector de entrada:

vector_input = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y_real = np.array([
    [0],
    [1],
    [1],
    [0]
])

# Inicilizando parametros aleatoriamente 
# Neuronas en filas

mu, sigma = 0, 0.1
w2 = np.random.normal(mu, sigma, 6).reshape(2,-1)
w3 = np.random.normal(mu, sigma, 6).reshape(3,-1)
w4 = np.random.normal(mu, sigma, 2).reshape(2,-1)

costo_capa4 = np.zeros(w4.shape)
costo_capa3 = np.zeros(w3.shape)
costo_capa2 = np.zeros(w2.shape)

In [706]:
lr = 0.01

for i in range(10):
    # Representaciones Intermedias
    H1 = np.matmul(vector_input, w2)
    act1 = relu(H1)

    H2 = np.matmul(act1, w3)
    act2 = relu(H2)

    H3 = np.matmul(act2, w4)
    vector_output = H3

    # Deltas
    error_salida = y_real - vector_output
    delta_capa3 = np.matmul(error_salida, w4.T)*der_relu(H2)
    delta_capa2 = np.matmul(delta_capa3, w3.T)*der_relu(H1)

    H1 = np.matmul(vector_input, w2)
    act1 = relu(H1)
    H2 = np.matmul(act1, w3)
    act2 = relu(H2)

    # Costos
    costo_capa4 = np.matmul(error_salida.T, act2)
    costo_capa3 = np.matmul(delta_capa3.T, act1)
    costo_capa2 = np.matmul(delta_capa2.T, vector_input)

    # Actualizacion de Costos
    costo_capa4 += costo_capa4
    costo_capa3 += costo_capa3
    costo_capa2 += costo_capa2

    # Gradiente Descent
    w2 = w2 - lr*costo_capa2.T
    w3 = w3 - lr*costo_capa3.T
    w4 = w4 - lr*costo_capa4.T
    
    print('resultado:', i, vector_output)
    print('error:', i, error_salida)

resultado: 0 [[0.00000000e+00]
 [7.26011422e-05]
 [0.00000000e+00]
 [2.65741922e-05]]
error: 0 [[ 0.00000000e+00]
 [ 9.99927399e-01]
 [ 1.00000000e+00]
 [-2.65741922e-05]]
resultado: 1 [[0.00000000e+00]
 [7.22392031e-05]
 [0.00000000e+00]
 [2.62706310e-05]]
error: 1 [[ 0.00000000e+00]
 [ 9.99927761e-01]
 [ 1.00000000e+00]
 [-2.62706310e-05]]
resultado: 2 [[0.00000000e+00]
 [7.18789464e-05]
 [0.00000000e+00]
 [2.59695636e-05]]
error: 2 [[ 0.00000000e+00]
 [ 9.99928121e-01]
 [ 1.00000000e+00]
 [-2.59695636e-05]]
resultado: 3 [[0.00000000e+00]
 [7.15203626e-05]
 [0.00000000e+00]
 [2.56709744e-05]]
error: 3 [[ 0.00000000e+00]
 [ 9.99928480e-01]
 [ 1.00000000e+00]
 [-2.56709744e-05]]
resultado: 4 [[0.00000000e+00]
 [7.11634426e-05]
 [0.00000000e+00]
 [2.53748477e-05]]
error: 4 [[ 0.00000000e+00]
 [ 9.99928837e-01]
 [ 1.00000000e+00]
 [-2.53748477e-05]]
resultado: 5 [[0.00000000e+00]
 [7.08081770e-05]
 [0.00000000e+00]
 [2.50811683e-05]]
error: 5 [[ 0.00000000e+00]
 [ 9.99929192e-01]
 [ 1.00