### **Nombre:** Elda Magally Calderón Motta
### **Carné:** 16003182
### **Sección:** U

# **TAREA 6**

# Primera Parte 

## Backward Propagation Delta (Error Simplificado)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Diagrama

<img src = 'http://imgfz.com/i/2AOBoZL.png'>

### Backward Propagation

In [2]:
# Vector error capa de salida
error_salida = np.array([[3,10]])

In [3]:
# Parametros capa 3
w_capa3 = np.array([
    [-0.23, 0.22, 0.77], 
    [0.9, 0.88, -0.4],
])

In [4]:
# Propagacion del error a la capa 3
error_capa3 = np.matmul(error_salida, w_capa3)

In [5]:
# Parametros capa 2
w_capa2 = np.array([
    [-0.3, 0.62, 0.45], 
    [0.45, 0.57, 0.48],
    [0.65, 0.58, -0.45]
])

In [6]:
# Propagacion del error a la capa 2
error_capa2 = np.matmul(error_capa3, w_capa2)

In [7]:
# Parametros capa 1
w_capa1 = np.array([
    [0.3, 0.46, 0.02], 
    [0.22, -0.7, 0.65],
    [0.65, 0.9, 0.34]
])

In [8]:
# Propagacion del error a la capa 1 (entrada)
error_capa1 = np.matmul(error_capa2, w_capa1)

In [9]:
# Errores por neurona

print('Error Neuronas Capa 1:', error_capa1)
print('Error Neuronas Capa 2:', error_capa2)
print('Error Neuronas Capa 3:', error_capa3)
print('Error Neuronas Capa Salida:', error_salida)

Error Neuronas Capa 1: [[8.180294 1.74791  9.303912]]
Error Neuronas Capa 2: [[0.6655 9.5642 9.0408]]
Error Neuronas Capa 3: [[ 8.31  9.46 -1.69]]
Error Neuronas Capa Salida: [[ 3 10]]


# Segunda Parte 

## Entrenar Aproximador para XOR

### Red Neuronal XOR

<img src = 'http://imgfz.com/i/aYX8w9y.jpeg'>

### Feedforward Propagation

In [10]:
# Vector de entrada:

vector_input = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y_real = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [70]:
# Inicilizando parametros aleatoriamente 
# Neuronas en filas

mu, sigma = 0, 0.1
w2 = np.random.normal(mu, sigma, 6).reshape(2,-1)
w3 = np.random.normal(mu, sigma, 6).reshape(3,-1)
w4 = np.random.normal(mu, sigma, 2).reshape(2,-1)

In [12]:
# Funcion Relu

def relu(x):
    a = x
    a[a < 0] = 0
    return a

In [71]:
# Representaciones Intermedias
H1 = np.matmul(vector_input, w2)
act1 = relu(H1)

In [72]:
H2 = np.matmul(act1, w3)
act2 = relu(H2)

In [73]:
H3 = np.matmul(act2, w4)
vector_output = H3

In [74]:
vector_output

array([[0.        ],
       [0.00023408],
       [0.00036588],
       [0.00058047]])

### Backward Propagation

In [18]:
# Funcion Derivada Relu

def der_relu(x):
    a = x
    a[a >= 0] = 1
    a[a < 0] = 0
    return (a)

In [76]:
# Error en Salida
error_salida = y_real - vector_output

In [77]:
delta_capa3 = np.matmul(error_salida, w4.T)*der_relu(H2)

In [78]:
delta_capa2 = np.matmul(delta_capa3, w3.T)*der_relu(H1)

In [90]:
dw4 = np.matmul(error_salida.T, act2) / len(vector_input)

In [91]:
dw3 = np.matmul(delta_capa3.T, act1) / len(vector_input)

In [92]:
dw2 = np.matmul(delta_capa2.T, vector_input) / len(vector_input)

In [93]:
# Gradiente Descent
lr = 0.1

w2 = w2 - lr*dw2.T
w3 = w3 - lr*dw3.T
w4 = w4 - lr*dw4.T

In [95]:
dw2

array([[0.00069026, 0.00069036],
       [0.00038278, 0.00038283],
       [0.00018336, 0.00018339]])

In [96]:
print(error_salida)

[[ 0.00000000e+00]
 [ 9.99765919e-01]
 [ 9.99634119e-01]
 [-5.80470729e-04]]


# Funcion

In [177]:
# Vector de entrada:

vector_input = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y_real = np.array([
    [0],
    [1],
    [1],
    [0]
])

# Inicilizando parametros aleatoriamente 
# Neuronas en filas

mu, sigma = 0, 0.1
w2 = np.random.normal(mu, sigma, 6).reshape(2,-1)
w3 = np.random.normal(mu, sigma, 6).reshape(3,-1)
w4 = np.random.normal(mu, sigma, 2).reshape(2,-1)

In [178]:
lr = 0.1

for i in range(300):
    # Representaciones Intermedias
    H1 = np.matmul(vector_input, w2)
    act1 = relu(H1)

    H2 = np.matmul(act1, w3)
    act2 = relu(H2)

    H3 = np.matmul(act2, w4)
    vector_output = H3

    # Deltas
    error_salida = vector_output - y_real
    delta_capa3 = np.matmul(error_salida, w4.T)*der_relu(H2)
    delta_capa2 = np.matmul(delta_capa3, w3.T)*der_relu(H1)

    H1 = np.matmul(vector_input, w2)
    act1 = relu(H1)
    H2 = np.matmul(act1, w3)
    act2 = relu(H2)

    # Derivadas Parciales Parametros
    dw4 = np.matmul(error_salida.T, act2) / len(vector_input)
    dw3 = np.matmul(delta_capa3.T, act1) / len(vector_input)
    dw2 = np.matmul(delta_capa2.T, vector_input) / len(vector_input)

    # Gradiente Descent
    w2 = w2 - lr*dw2.T
    w3 = w3 - lr*dw3.T
    w4 = w4 - lr*dw4.T
    
    if i % 20 == 0:
        print('resultado:', i, vector_output)
        print('error:', i, error_salida)
        

resultado: 0 [[0.00000000e+00]
 [2.80734203e-04]
 [0.00000000e+00]
 [2.86945324e-05]]
error: 0 [[ 0.00000000e+00]
 [-9.99719266e-01]
 [-1.00000000e+00]
 [ 2.86945324e-05]]
resultado: 20 [[0.        ]
 [0.00032861]
 [0.        ]
 [0.00010221]]
error: 20 [[ 0.00000000e+00]
 [-9.99671393e-01]
 [-1.00000000e+00]
 [ 1.02214566e-04]]
resultado: 40 [[0.        ]
 [0.00038338]
 [0.        ]
 [0.00018598]]
error: 40 [[ 0.00000000e+00]
 [-9.99616622e-01]
 [-1.00000000e+00]
 [ 1.85979645e-04]]
resultado: 60 [[0.        ]
 [0.00044663]
 [0.        ]
 [0.00028266]]
error: 60 [[ 0.00000000e+00]
 [-9.99553372e-01]
 [-1.00000000e+00]
 [ 2.82656138e-04]]
resultado: 80 [[0.        ]
 [0.00052033]
 [0.        ]
 [0.0003956 ]]
error: 80 [[ 0.00000000e+00]
 [-9.99479667e-01]
 [-1.00000000e+00]
 [ 3.95595756e-04]]
resultado: 100 [[0.        ]
 [0.00060701]
 [0.        ]
 [0.00052907]]
error: 100 [[ 0.00000000e+00]
 [-9.99392995e-01]
 [-1.00000000e+00]
 [ 5.29067995e-04]]
resultado: 120 [[0.        ]
 [0.000